attack_label_trans: all2one
attack_target: 6
pratio: 0.005
attack: narcissus
narcissus_noise_path: ../resource/narcissus/checkpoint/narcissus_noise_cls_6.npy
batch_size: 150
random_seed: 65
epoch: 200
lr: 0.1
### For naive cover test, useless here
cratio: 0
add_cover: 0