attack_label_trans: all2one
attack_target: 2
pratio: 0.005
attack: natsteg
narcissus_noise_path: ../resource/narcissus/checkpoint/narcissus_noise_cls_2.npy
steg_net_path: ../resource/natsteg/checkpoint/natsteg_tiny_cifar_cls_2.pth
batch_size: 150
random_seed: 65
epoch: 200
lr: 0.1
### For naive cover test, useless here
cratio: 0
add_cover: 0